apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "helpers.ns" . }}
  name: {{ include "helpers.name" . }}
stringData:
  {{ range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | default "" | quote }}
  {{ end }}
---
{{ $ns := include "helpers.ns" . }}
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  namespace: {{ $ns }}
  name: entreeqr-ghcr-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJiR2xoZFdkMWMzUTZaMmh3WDFZMGMwbFhTell4VTB0WWJIbGFOSEpCVFhWTFVtRnZkMDlNZVZOUlFqSkxVVVJ0VkE9PSIsCiAgICAgICJlbWFpbCI6ICJpdmFuLmxpYXVndXN0QGdtYWlsLmNvbSIKICAgIH0KICB9Cn0=