import NextHead from "next/head";
import { FC } from "react";

const Head: FC = () => {
  return (
    <NextHead>
      <title>Entree</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.svg" />
    </NextHead>
  );
};

export default Head;
